//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Rhino")]
[assembly: AssemblyCopyright("Oren Eini (c) 2006 - 2008")]
[assembly: AssemblyDescription("Rhino.Security")]
[assembly: AssemblyInformationalVersion("0.9.1093")]
[assembly: AssemblyTitle("Rhino.Security")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("0.9.1093")]


